### ISSUE TITLE
Brak poprwności, chociaż z przykładami wszystko się zgadza

### ISSUE THREAD

**Issue by mkowals9** [korona-science/homework-mkowals9#1]

**Comment by Torisels** [comment]
W zadaniu drugim zwracany typ nie jest typu `List` a `numpy.ndarray`, który prawdopodobnie ewaluowany jest do stringa. Polecam zmianę rozwiązania, np. `tolist()`.

**Comment by mkowals9** [comment]
Dzięki, właśnie to było złe 🥰

**Comment by RouNNdeL** [comment]
Testy przeszły
